# Config file for automatic testing at travis-ci.org

language: python

matrix:
    include:
      - python: 3.4
        env: TOX_ENV=py34
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: "3.7-dev"
        env: TOX_ENV=py37
      - python: 3.6
        env: TOX_ENV=flake8

install:
  - pip install tox
  - pip install psutil

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
